### ISSUE TITLE
forme -V and all forme commands return an empty result every time

### ISSUE THREAD

**Issue by vincenzocasu** [formewp/forme-codegen#1]
```
Mac-Studio-di-Vincenzo:~ vincenzocasu$ forme -V
Mac-Studio-di-Vincenzo:~ vincenzocasu$ forme list
Mac-Studio-di-Vincenzo:~ vincenzocasu$ 

Mac-Studio-di-Vincenzo:~ vincenzocasu$ php -v
PHP 8.3.11 (cli) (built: Aug 27 2024 19:16:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.11, Copyright (c), by Zend Technologies

Mac-Studio-di-Vincenzo:bin vincenzocasu$ /usr/bin/env php -v
PHP 8.3.11 (cli) (built: Aug 27 2024 19:16:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.11, Copyright (c), by Zend Technologies

Mac-Studio-di-Vincenzo:~ vincenzocasu$ mysql -V
mysql from 11.5.2-MariaDB, client 15.2 for osx10.19 (arm64) using  EditLine wrapper

Mac-Studio-di-Vincenzo:~ vincenzocasu$ node -v
v22.9.0

```
I followed the detailed guide and the environment seems up to date.

Where can I find a way to fix this? What am I missing?

**Comment by moussaclarke** [comment]
Is there anything relevant in your php cli logs maybe? You could also try setting `error_reporting` to `E_ALL` in `path/to/your/global/composer/vendor/forme/codegen/forme`  and run `forme -V` or `forme list` again to see if you get any useful error output.

**Comment by moussaclarke** [comment]
Could you also check `composer global show` and make sure the latest version of forme codegen is installed, should be 2.3.2 (as of this comment's date)

**Comment by vincenzocasu** [comment]
> Could you also check `composer global show` and make sure the latest version of forme codegen is installed, should be 2.3.2 (as of this comment's date)

Version is 2.3.2 as of this comment's date

But setting up E_ALL flag this error comes out with the command -V

```
Mac-Studio-di-Vincenzo:~ vincenzocasu$ forme -V

Fatal error: Type of Forme\CodeGen\Command\MakeCommand::$defaultName must not be defined (as in class Symfony\Component\Console\Command\Command) in /Users/vincenzocasu/.composer/vendor/forme/codegen/src/Command/MakeCommand.php on line 20
Mac-Studio-di-Vincenzo:~ vincenzocasu$ 
```

**Comment by moussaclarke** [comment]
OK I think I see what the problem might be - what version of `symfony/console` does `composer global show` have?

Do you have any other global composer installations that have `symfony/console` v6 as a dependency?

I'll see if I can push a fix asap so that it works with `symfony/console` v6 - otherwise in the meantime you could move up to `symfony/console`  v7.1.5

**Comment by moussaclarke** [comment]
Assuming you are running symfony/console v6, please try v2.3.3 - just pushed a fix so it hopefully should with that version again

https://github.com/formewp/forme-codegen/commit/c4a4387c83db69b8cd6fa416aec46515d98d1c14

**Comment by vincenzocasu** [comment]
Thank you so much for your precious help! I updated laravel/valet which was to a version that did not allow composer to update symfony/console beyond version 6.4.

Now the forme command works correctly!

Now comes the fun part, because there will be a lot of fun with formewp 💪🏻👨🏻‍💻🫶🏻

**Comment by vincenzocasu** [comment]
I'm afraid there's still something not quite right.

When I launch the command: 


forms new --view=twig plugin HelloWorld


I get the output: 

🌱 Generating new project... The authenticity of host 'github.com (140.82.121.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
 350/350 [=============================] 100% 🎉 Created a new Forme plugin project! You can cd into hello-world-plugin and get coding!

but I can't find any hello-world-plugin folder and in the directory from which I launched the command I only find these two files

Mac-Studio-di-Vincenzo:formewp-dev vincenzocasu $ ls
cliff.toml package-lock.json

Even though I know it's not a privilege issue because I'm in a directory where I have full permissions for my user, I also tried running the command with higher privileges using sudo, but the result is the same.

I set the error flag back to E_ALL, but no particular warning comes up.

This is the composer global show output:

Mac-Studio-di-Vincenzo:formewp-dev vincenzocasu$ composer global show
Changed current directory to /Users/vincenzocasu/.composer
brick/math                                     0.12.1   Arbitrary-precision arithmetic library
cakephp/chronos                                3.1.0    A simple API extension for DateTime.
cakephp/core                                   5.1.0    CakePHP Framework Core classes
cakephp/database                               5.1.0    Flexible and powerful Database abstraction library with a familiar PDO-lik...
cakephp/datasource                             5.1.0    Provides connection managing and traits for Entities and Queries that can ...
cakephp/utility                                5.1.0    CakePHP Utility classes such as Inflector, String, Hash, and Security
carbonphp/carbon-doctrine-types                2.1.0    Types to use Carbon in Doctrine
cebe/markdown                                  1.2.1    A super fast, highly extensible markdown parser for PHP
clue/ndjson-react                              1.3.0    Streaming newline-delimited JSON (NDJSON) parser and encoder for ReactPHP.
composer/pcre                                  3.3.1    PCRE wrapping library that offers type-safe preg_* replacements.
composer/semver                                3.4.3    Semver library that offers utilities, version constraint parsing and valid...
composer/xdebug-handler                        3.0.5    Restarts a process without Xdebug.
consolidation/comments                         1.0.2    A tool for preserving comments, e.g. when parsing YAML files.
dealerdirect/phpcodesniffer-composer-installer 1.0.0    PHP_CodeSniffer Standards Composer Installer Plugin
doctrine/inflector                             2.0.10   PHP Doctrine Inflector is a small library that can perform string manipula...
evenement/evenement                            3.0.2    Événement is a very simple event dispatching library for PHP
fidry/cpu-core-counter                         1.2.0    Tiny utility to get the number of CPU cores.
forme/codegen                                  2.3.3    Code Generation CLI For The Forme WordPress Framework
forme/framework                                3.9.4    An MVC framework for WordPress.
friendsofphp/php-cs-fixer                      3.64.0   A tool to automatically fix PHP code style
graham-campbell/result-type                    1.1.3    An Implementation Of The Result Type
guzzlehttp/guzzle                              7.9.2    Guzzle is a PHP HTTP client library
guzzlehttp/promises                            2.0.3    Guzzle promises library
guzzlehttp/psr7                                2.7.0    PSR-7 message implementation that also provides common utility methods
http-interop/response-sender                   1.0.0    A function to convert PSR-7 Response to HTTP output
illuminate/bus                                 10.48.22 The Illuminate Bus package.
illuminate/collections                         10.48.22 The Illuminate Collections package.
illuminate/conditionable                       10.48.22 The Illuminate Conditionable package.
illuminate/config                              10.48.22 The Illuminate Config package.
illuminate/container                           10.48.22 The Illuminate Container package.
illuminate/contracts                           10.48.22 The Illuminate Contracts package.
illuminate/database                            10.48.22 The Illuminate Database package.
illuminate/events                              10.48.22 The Illuminate Events package.
illuminate/filesystem                          10.48.22 The Illuminate Filesystem package.
illuminate/macroable                           10.48.22 The Illuminate Macroable package.
illuminate/pipeline                            10.48.22 The Illuminate Pipeline package.
illuminate/support                             10.48.22 The Illuminate Support package.
illuminate/view                                10.48.22 The Illuminate View package.
jawira/case-converter                          3.5.1    Convert strings between 13 naming conventions: Snake case, Camel case, Pas...
jolicode/jolinotif                             2.7.2    Send desktop notifications on Windows, Linux, MacOS.
jolicode/php-os-helper                         0.1.0    Helpers to detect the OS of the machine where PHP is running.
laminas/laminas-diactoros                      3.4.0    PSR HTTP Message implementations
laravel/prompts                                0.1.25   Add beautiful and user-friendly forms to your command-line applications.
laravel/serializable-closure                   1.3.5    Laravel Serializable Closure provides an easy and secure way to serialize ...
laravel/valet                                  4.8.0    A more enjoyable local development experience for Mac.
league/container                               4.2.2    A fast and intuitive dependency injection container.
league/flysystem                               3.28.0   File storage abstraction for PHP
league/flysystem-local                         3.28.0   Local filesystem adapter for Flysystem.
league/mime-type-detection                     1.16.0   Mime-type detection for Flysystem
league/plates                                  3.5.0    Plates, the native PHP template system that's fast, easy to use and easy t...
log1x/sage-directives                          2.0.5    A set of Blade directives for use with Roots Sage.
mnapoli/silly                                  1.9.0    Silly CLI micro-framework based on Symfony Console
monolog/monolog                                3.7.0    Sends your logs to files, sockets, inboxes, databases and various web serv...
nesbot/carbon                                  2.72.5   An API extension for DateTime that supports 281 different languages.
nette/php-generator                            4.1.6    🐘 Nette PHP Generator: generates neat PHP code for you. Supports new PH...
nette/utils                                    3.2.10   🛠  Nette Utils: lightweight utilities for string & array manipulation, ...
nikic/php-parser                               4.19.2   A PHP parser written in PHP
papertower/wp-rest-api-psr7                    0.8      Provides PSR-7 and WP REST API Response and Request classes
php-di/invoker                                 2.3.4    Generic and extensible callable invoker
php-di/php-di                                  7.0.7    The dependency injection container for humans
phpcsstandards/phpcsextra                      1.2.1    A collection of sniffs and standards for use with PHP_CodeSniffer.
phpcsstandards/phpcsutils                      1.0.12   A suite of utility functions for use with PHP_CodeSniffer
phpoption/phpoption                            1.9.3    Option Type for PHP
phppkg/cli-markdown                            2.0.2    Render colored markdown contents on console terminal
psr/clock                                      1.0.0    Common interface for reading the clock.
psr/container                                  2.0.2    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                           1.0.0    Standard interfaces for event handling.
psr/http-client                                1.0.3    Common interface for HTTP clients
psr/http-factory                               1.1.0    PSR-17: Common interfaces for PSR-7 HTTP message factories
psr/http-message                               1.1      Common interface for HTTP messages
psr/http-server-handler                        1.0.2    Common interface for HTTP server-side request handler
psr/http-server-middleware                     1.0.2    Common interface for HTTP server-side middleware
psr/log                                        3.0.2    Common interface for logging libraries
psr/simple-cache                               3.0.0    Common interfaces for simple caching
ralouphie/getallheaders                        3.0.3    A polyfill for getallheaders.
ramsey/collection                              2.0.0    A PHP library for representing and manipulating collections.
ramsey/uuid                                    4.7.6    A PHP library for generating and working with universally unique identifie...
rareloop/psr7-server-request-extension         2.1.0   
react/cache                                    1.2.0    Async, Promise-based cache interface for ReactPHP
react/child-process                            0.6.5    Event-driven library for executing child processes with ReactPHP.
react/dns                                      1.13.0   Async DNS resolver for ReactPHP
react/event-loop                               1.5.0    ReactPHP's core reactor event loop that libraries can use for evented I/O.
react/promise                                  3.2.0    A lightweight implementation of CommonJS Promises/A for PHP
react/socket                                   1.16.0   Async, streaming plaintext TCP/IP and secure TLS socket server and client ...
react/stream                                   1.4.0    Event-driven readable and writable streams for non-blocking I/O in ReactPHP
relay/relay                                    2.1.2    A PSR-15 server request handler.
robmorgan/phinx                                0.15.5   Phinx makes it ridiculously easy to manage the database migrations for you...
sebastian/diff                                 6.0.2    Diff implementation
spatie/enum                                    3.13.0   PHP Enums
squizlabs/php_codesniffer                      3.10.3   PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violat...
symfony/config                                 7.1.1    Helps you find, load, combine, autofill and validate configuration values ...
symfony/console                                7.1.5    Eases the creation of beautiful and testable command line interfaces
symfony/deprecation-contracts                  3.5.0    A generic function and convention to trigger deprecation notices
symfony/event-dispatcher                       7.1.1    Provides tools that allow your application components to communicate with ...
symfony/event-dispatcher-contracts             3.5.0    Generic abstractions related to dispatching event
symfony/filesystem                             7.1.5    Provides basic utilities for the filesystem
symfony/finder                                 6.4.11   Finds files and directories via an intuitive fluent interface
symfony/options-resolver                       7.1.1    Provides an improved replacement for the array_replace PHP function
symfony/polyfill-ctype                         1.31.0   Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme                 1.31.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer               1.31.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                      1.31.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php80                         1.31.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81                         1.31.0   Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                                6.4.12   Executes commands in sub-processes
symfony/service-contracts                      3.5.0    Generic abstractions related to writing services
symfony/stopwatch                              7.1.1    Provides a way to profile code
symfony/string                                 6.4.12   Provides an object-oriented API to strings and deals with bytes, UTF-8 cod...
symfony/translation                            6.4.12   Provides tools to internationalize your application
symfony/translation-contracts                  3.5.0    Generic abstractions related to translation
symfony/yaml                                   6.4.12   Loads and dumps YAML files
symplify/coding-standard                       11.4.1   Set of Symplify rules for PHP_CodeSniffer and PHP CS Fixer.
symplify/easy-coding-standard                  11.5.0   Use Coding Standard with 0-knowledge of PHP-CS-Fixer and PHP_CodeSniffer
symplify/rule-doc-generator-contracts          11.2.0   Contracts for production code of RuleDocGenerator
toolkit/cli-utils                              2.0.3    useful cli tool library of the php
twig/twig                                      3.14.0   Twig, the flexible, fast, and secure template language for PHP
vlucas/phpdotenv                               5.6.1    Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERV...
voku/portable-ascii                            2.0.1    Portable ASCII library - performance optimized (ascii) string functions fo...
wp-coding-standards/wpcs                       3.1.0    PHP_CodeSniffer rules (sniffs) to enforce WordPress coding conventions

do you have any ideas?

**Comment by moussaclarke** [comment]
Hmm yes that's strange. The directory should be created by the underlying git clone command, and the fact that the cliff.toml and package-lock.json files exist suggests neither github connection nor permissions at fault.

Does it work if you try it a second time?

Otherwise, the only thing I can suggest is to try to run the install commands from https://github.com/formewp/forme-codegen/blob/main/src/Shell/new_project.sh manually in your terminal, check it at each step, and see if that throws any errors. For example, you could try:

```bash
git clone git@github.com:formewp/forme-plugin.git hello-world-plugin
cd hello-world-plugin
rm -rf .git
npm i
npx gulp --name="HelloWorld" --vendor="App" --view="twig"
rm gulpfile.js
rm -rf node_modules
rm package.json
rm package-lock.json
mv package.json.stub package.json
npm i
git cliff --init
composer install
git init
git add --all
git commit --all -m "Initial Commit"
composer hooks
cd ..
```

**Comment by moussaclarke** [comment]
Just to clarify, the above commands are what `forme new --view=twig plugin HelloWorld`  should be trying to run under the hood - see https://github.com/formewp/forme-codegen/blob/main/src/Command/NewCommand.php and https://github.com/formewp/forme-codegen/blob/main/src/Utils/NewShellScriptReplacer.php - it basically takes the provided cli arguments and swaps them in to the shell script in https://github.com/formewp/forme-codegen/blob/main/src/Shell/new_project.sh

**Comment by vincenzocasu** [comment]
It was a ssh key issue, which strangely was not taken by github. I regenerated it and now it's ok!

You were really very kind! Thank you very much!
